# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

target 'capstone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for capstone

  target 'capstoneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'capstoneUITests' do
    # Pods for testing
  end

end
